name: 'Magento 2 Coding Standard'
author: '121eCommerce LLC'
description: 'Performs PHP static code analysis with the Magento 2 Coding Standard'
inputs:
  path_to_code:
    description: 'Relative path to the code.'
    required: false
    default: ''
  phpcs_extensions:
    description: 'List of file extensions to check.'
    required: false
runs:
  using: 'docker'
  image: 'docker://dmitryfurs/github-action-magento-coding-standard:latest'
branding:
  icon: 'code'
  color: 'green'
