name: 'Inline Styles'
author: '121eCommerce LLC'
description: 'Performs search for inline styles by the extension list.'
branding:
  icon: 'code'
  color: 'green'
inputs:
  path-to-code:
    description: 'Relative path to the code.'
    required: false
    default: '/'
  file-extensions:
    description: 'File Extensions.'
    required: false
    default: 'php phtml html'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Detect Inline Styles
      run: |
        found=false
        cd ${{ github.workspace }}${{ inputs.path-to-code }}
        extensions=(${{ inputs.file-extensions }})
        for extension in ${extensions[@]}; do
          for file in $(find $(pwd -P) -type f -name '*.'${extension}); do
            for line in $(grep -n "style=" $file | cut -d: -f1); do
              found=true
              echo "::error file=$file,line=$line::The inline styles are bad practice and increase the size of html page."
            done
          done
        done
        if [ $found == 'true' ]; then
          exit 1
        fi
      shell: bash
