name: 'Magento 2 Mess Detector'
author: '121eCommerce LLC'
description: 'Performs PHP static code analysis with the Magento 2 Mess Detector ruleset'
branding:
  icon: 'code'
  color: 'green'
inputs:
  php_version:
    description: 'PHP Version'
    required: false
    default: '8.2'
  php_extensions:
    description: 'PHP Extensions'
    required: false
    default: 'gd, bcmath, soap, pdo_mysql, ctype, curl, dom, hash, iconv, intl, mbstring, openssl, simplexml, xsl, sockets, zip'
  composer_version:
    description: 'Composer Version'
    required: false
    default: 'v2'
  path_to_code:
    description: 'Relative path to the code.'
    required: false
    default: '/'
  ruleset:
    description: 'Relative path to ruleset file.'
    required: false
    default: './dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup PHP Action
      uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: ${{ inputs.php_version }}
        tools: composer:${{ inputs.composer_version }}
        extensions: ${{ inputs.php_extensions }}
    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Run "composer install"
      run: composer install --prefer-dist --no-progress
      shell: bash
    - name: Run PHPMD analysis
      run: ./vendor/bin/phpmd ${{ github.workspace }}${{ inputs.path_to_code }} github ${{ inputs.ruleset }} --suffixes php,phtml
      shell: bash
