name: Magento 2 Mess Detector
author: 121eCommerce LLC
description: Performs PHP static code analysis with the Magento 2 Mess Detector ruleset
branding:
  icon: code
  color: green
inputs:
  php_version:
    description: PHP Version
    required: false
    default: 8.2
  php_extensions:
    description: PHP Extensions
    required: false
    default: gd, bcmath, soap, pdo_mysql, ctype, curl, dom, hash, iconv, intl, mbstring, openssl, simplexml, xsl, sockets, zip
  composer_version:
    description: Composer Version
    required: false
    default: v2
  path_to_code:
    description: Relative path to the code.
    required: false
    default: /
  ruleset:
    description: Relative path to ruleset file.
    required: false
    default: ./dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml
  skip-cache:
    description: Skip composer cache.
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Setup PHP Action
      uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: ${{ inputs.php_version }}
        tools: composer:${{ inputs.composer_version }}
        extensions: ${{ inputs.php_extensions }}
    - name: Get Composer global directories
      id: composer
      run: |
        echo "dir-cache=$(composer global config cache-files-dir --absolute --quiet)" >> $GITHUB_OUTPUT
        echo "dir-bin=$(composer global config bin-dir --absolute --quiet)" >> $GITHUB_OUTPUT
        echo "dir-vendor=$(composer global config vendor-dir --absolute --quiet)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Restore Composer Cache
      if: ${{ !inputs.skip-cache }}
      id: cache
      uses: actions/cache/restore@v3
      with:
        path: ${{ steps.composer.outputs.dir-cache }}
        key: ${{ runner.os }};composer.lock=${{ hashFiles('**/composer.lock') }};
    - name: Run "composer install"
      run: composer install --prefer-dist --no-progress
      shell: bash
    - name: Save Composer Cache
      if: ${{ steps.cache.outputs.cache-hit != 'true' && !inputs.skip-cache }}
      uses: actions/cache/save@v3
      with:
        path: ${{ steps.composer.outputs.dir-cache }}
        key: ${{ runner.os }};composer.lock=${{ hashFiles('**/composer.lock') }};
    - name: Run PHPMD analysis
      run: ./vendor/bin/phpmd ${{ github.workspace }}${{ inputs.path_to_code }} github ${{ inputs.ruleset }} --suffixes php,phtml
      shell: bash
