name: 'Magento 2 Mess Detector'
author: '121eCommerce LLC'
description: 'Performs PHP static code analysis with the Magento 2 Mess Detector ruleset'
branding:
  icon: 'code'
  color: 'green'
inputs:
  php_version:
    description: 'PHP Version'
    required: false
    default: '8.2'
  php_extensions:
    description: 'PHP Extensions'
    required: false
    default: 'gd, bcmath, soap, pdo_mysql, ctype, curl, dom, hash, iconv, intl, mbstring, openssl, simplexml, xsl, sockets, zip'
  composer_version:
    description: 'Composer Version'
    required: false
    default: 'v2'
  path_to_code:
    description: 'Relative path to the code.'
    required: false
    default: '/'
  ruleset:
    description: 'Relative path to ruleset file.'
    required: false
    default: ''
  phpmd-version:
    description: 'PHP Mess Detector Composer Version.'
    required: false
    default: '*'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Setup PHP Action
      uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: ${{ inputs.php_version }}
        tools: composer:${{ inputs.composer_version }}
        extensions: ${{ inputs.php_extensions }}
    - name: Get composer global cache directory
      id: composer-cache
      run: echo "dir-cache=$(composer global config cache-files-dir --absolute --quiet)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cache global dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir-cache }}
        key: ${{ runner.os }}-phpmd-${{ inputs.phpmd-version }}
        restore-keys: ${{ runner.os }}-phpmd-${{ inputs.phpmd-version }}
    - name: Require PHPMD
      run: composer global require phpmd/phpmd:${{ inputs.phpmd-version }}
      shell: bash
    - name: Get composer bin directory
      id: composer-bin
      run: echo "dir-bin=$(composer global config bin-dir --absolute --quiet)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Run specific ruleset
      if:  ${{ inputs.ruleset }}
      run: ${{ steps.composer-bin.outputs.dir-bin }}/phpmd ${{ github.workspace }}${{ inputs.path_to_code }} github ${{ github.workspace }}${{ inputs.ruleset }} --suffixes php,phtml
      shell: bash
    - name: Run default ruleset
      if:  ${{ !inputs.ruleset }}
      run: ${{ steps.composer-bin.outputs.dir-bin }}/phpmd ${{ github.workspace }}${{ inputs.path_to_code }} github ${{ github.action_path }}/ruleset.xml --suffixes php,phtml
      shell: bash
